__include__: abstract.yaml
exp:
  dir: logs/MSEmbedding/23_trainingDatasets_radam_lstm_20_LR1e-2_margin0.3_700_epochs_wd1e-5_adaptive_epsilon_1e-6_bi-lstm_singleState
dataset:
  train_filtered_files_list: ['b01', 'b03', 'b04', 'b05', 'b06', 'b07', 'b08', 'b09', 'b10', 'b11', 'b12', 'b13', 'b14', 'b15', 'b16', 'b17', 'b18', 'b19', 'b20', 'b21', 'b22', 'b23', 'b24']
  train_peaks_file: train_b01_03_04_05_06_07_08_09_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24.pkl

  # eval_matches_file: adult_adrenalgland_bRP_velos.csv
  # eval_filtered_files_list: ['A1', 'B4', 'C11']
  # eval_peaks_file: eval_adult_adrenalgland_bRP_velos_A1_B4_C11.pkl

  # eval_matches_file: fetal_brain_gel_velos_16.csv
  # eval_filtered_files_list: ['E1', 'E8', 'F9']
  # eval_peaks_file: eval_fetal_brain_gel_velos_E1_E8_F9.pkl

  # eval_matches_file: adult_adrenalgland_gel_velos.csv
  # eval_filtered_files_list: ['D3', 'E3', 'E7']
  # eval_peaks_file: eval_adult_adrenalgland_gel_velos_D3_E3_E7.pkl

  # eval_matches_file: adult_urinarybladder_gel_elite.csv
  # eval_filtered_files_list: ['b1', 'b12', 'b24']
  # eval_peaks_file: eval_urinarybladder_gel_elite_b1_b12_b24.pkl

  eval_matches_file: adult_platelets_gel_elite.csv
  eval_filtered_files_list: ['b1', 'b18', 'b24']
  eval_peaks_file: eval_adult_platelets_gel_elite_b1_b18_b24.pkl

  batch_size: 200
engine:
  nb_epochs: 700
model:
  network:
    lstm_out_dim: 20
    bidirecional_lstm: True
  criterion:
    name: MatrixTripletMargin
    aggregation: valid
    epsilon: 0.0000001
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: radam
  lr: 0.001 
  weight_decay: 0.00001
misc:
  cuda: True
