__include__: abstract.yaml
exp:
    dir: logs/MSEmbedding/23_trainingDatasets_allNorm_cosine_madamw_lstm_30_LR1e-3_margin0.3_200_epochs_wd1e-5_matrixCriterion_packed_adaptive
dataset:
  train_filtered_files_list: ['b01', 'b03', 'b04', 'b05', 'b06', 'b07', 'b08', 'b09', 'b10', 'b11', 'b12', 'b13', 'b14', 'b15', 'b16', 'b17', 'b18', 'b19', 'b20', 'b21', 'b22', 'b23', 'b24']
  train_peaks_file: train_b01_03_04_05_06_07_08_09_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24.pkl
  batch_size: 702
engine:
  nb_epochs: 200
model:
  network:
    lstm_out_dim: 30
  criterion:
    name: MatrixTripletMargin
    aggregation: valid    
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: madamw
  lr: 0.001
  weight_decay: 0.00001
misc:
  cuda: True
