__include__: abstract.yaml
exp:
    dir: logs/MSEmbedding/4_trainingDatasets_normalized_LR10-3
dataset:
  train_filtered_files_list: ['b01', 'b03', 'b04', 'b05']
  train_peaks_file: train_b01_03_04_05.pkl
optimizer:
  lr: 0.001
misc:
  cuda: True
