__include__: abstract.yaml
exp:
    dir: logs/MSEmbedding/4_trainingDatasets_normalized_lstm_20
dataset:
  train_filtered_files_list: ['b01', 'b03', 'b04', 'b05']
  train_peaks_file: train_b01_03_04_05.pkl
  batch_size: 1002
engine:
  nb_epochs: 100  
model:
  network:
    lstm_out_dim: 20
  criterion:
    name: MatrixTripletMargin
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: madamw
  lr: 0.01 
  weight_decay: 0.00001
misc:
  cuda: True
   