__include__: abstract.yaml
exp:
  dir: logs/MSEmbedding/encode_training_lstm_80_3_layers_double_n_pair_margin_0.5_LR1e-2_q0.001_all_pvalue_0.6
dataset:
  name: linfeng
  dir: data/linfeng_all_q0.001_n_pair
  mgf_dir: /media/eduseiti/bigdata01/unicamp/doutorado/clustering/linfeng/sample/pvalue/PXD000561/for_identification
  mgf_experiments: PXD000561_SAMPLE_FOLDER
  spectra_list_file: sample_PXD000561_q0.001_all_pvalue_0.6_double_n_pair_margin_0.5_lstm80
  embeddings_file: sample_PXD000561_q0.001_all_lstm80_3layer_pvalue_0.6_double_n_pair_margin_0.5
  embeddings_dir: data/linfeng_all_q0.001_n_pair
  train_split: 
  eval_split: test
  train_normalization_file: data/mixedSpectraCrux/sequences/train_mixedSpectraCrux_v7.2.pkl
  batch_size: 400
  nb_threads: 0  
engine:
  nb_epochs: 1
model:
  name: MSEmbedding_encoding
  network:
    lstm_out_dim: 80
    bidirecional_lstm: True
    num_of_layers: 3
  metric:
    name: saveEmbeddings
    import: MSEmbedding.models.metrics.factory    
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: radam
  lr: 0.001 
  weight_decay: 0.00001
misc:
  cuda: True
views:
  items:  
    - logs:eval_epoch.metric.MedR
    - logs:eval_epoch.metric.recall_at_1
    - logs:eval_epoch.metric.recall_at_5
    - logs:eval_epoch.metric.recall_at_10
