__include__: abstract.yaml
exp:
  dir: logs/MSEmbedding/mixedSpectraCrux_all_lstm_80_3_layers_n_m_tuplet_clusters_q0.001_pvalue_0.6
dataset:
  name: mixedSpectraCrux
  dir: data/mixedSpectraCrux
  train_set_version: v7.2
  eval_set_version: v7.2
  max_pvalue: -53.19835
  batch_size: 300
  winsorizing_index: 0
  max_validation_samples: 5000
engine:
  nb_epochs: 1000
  saving_criteria:
  - eval_epoch.metric.MedR:min
  - eval_epoch.metric.recall_at_10:max  
  - eval_epoch.metric.recall_at_1:max  
model:
  network:
    lstm_out_dim: 40
    bidirecional_lstm: True
    num_of_layers: 3
  criterion:
    name: NMTupletClusters
    aggregation: valid
    epsilon: 0.00000001
    loss_margin: 0.6
    reference_distance: 0.3
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: radam
  lr: 0.0001 
  weight_decay: 0.00001
misc:
  cuda: True
views:
  items:  
    - logs:train_batch.loss
    - logs:train_epoch.loss
    - logs:eval_batch.loss
    - logs:eval_epoch.loss
    - logs:eval_epoch.metric.MedR
    - logs:eval_epoch.metric.recall_at_1
    - logs:eval_epoch.metric.recall_at_5
    - logs:eval_epoch.metric.recall_at_10
