__include__: abstract.yaml
exp:
  dir: logs/MSEmbedding/mixedSpectraCrux_all_lstm_40_3_layers_LR1e-3_margin0.3_q0.01_pvalue_0.1_test
dataset:
  name: mixedSpectraCrux
  dir: data/mixedSpectraCrux
  train_set_version: v5.1
  eval_set_version: v5.1
  # train_set_version: v6.0
  # eval_set_version: v6.0
  max_pvalue: -63.91164
  batch_size: 350
engine:
  nb_epochs: 1000
model:
  network:
    lstm_out_dim: 40
    bidirecional_lstm: True
    num_of_layers: 3
  criterion:
    name: MatrixTripletMargin
    aggregation: valid
    epsilon: 0.000001
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: radam
  lr: 0.001 
  weight_decay: 0.00001
misc:
  cuda: True
views:
  items:  
    - logs:train_batch.loss
    - logs:train_epoch.loss
    - logs:eval_batch.loss
    - logs:eval_epoch.loss
    - logs:eval_epoch.metric.MedR
    - logs:eval_epoch.metric.recall_at_1
    - logs:eval_epoch.metric.recall_at_5
    - logs:eval_epoch.metric.recall_at_10
