__include__: abstract.yaml
exp:
    dir: logs/MSEmbedding/23_trainingDatasets_radam_lstm_30_LR1e-4_margin0.3_700_epochs_wd1e-5_adaptive_epsilon_1e-6
dataset:
  train_filtered_files_list: ['b01', 'b03', 'b04', 'b05', 'b06', 'b07', 'b08', 'b09', 'b10', 'b11', 'b12', 'b13', 'b14', 'b15', 'b16', 'b17', 'b18', 'b19', 'b20', 'b21', 'b22', 'b23', 'b24']
  train_peaks_file: train_b01_03_04_05_06_07_08_09_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24.pkl
  batch_size: 600
engine:
  nb_epochs: 700
model:
  network:
    lstm_out_dim: 30
  criterion:
    name: MatrixTripletMargin
    aggregation: valid
    epsilon: 0.000001
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: radam
  lr: 0.0001
  weight_decay: 0.00001
misc:
  cuda: True
