__include__: abstract.yaml
exp:
  dir: logs/MSEmbedding/mixedSpectraCrux_big_radam_lstm_40_LR1e-3_margin0.48_1000_epochs_wd1e-5_adaptive_epsilon_1e-6_bi-lstm_3_layers_q0.001
dataset:
  name: mixedSpectraCrux
  dir: data/mixedSpectraCrux
  train_set_version: v3.1
  eval_set_version: v3.1
  batch_size: 700
engine:
  nb_epochs: 1000
  saving_criteria:
  - eval_epoch.metric.MedR:min
#  - eval_epoch.metric.recall_at_10:max
model:
  network:
    lstm_out_dim: 40
    bidirecional_lstm: True
    num_of_layers: 3
  criterion:
    name: MatrixTripletMargin
    aggregation: valid
    epsilon: 0.000001
    loss_margin: 0.48
optimizer:
  import: MSEmbedding.models.optimizers.factory
  name: radam
  lr: 0.001
  weight_decay: 0.00001
misc:
  cuda: True
views:
  items:  
    - logs:train_batch.loss
    - logs:train_epoch.loss
    - logs:eval_batch.loss
    - logs:eval_epoch.loss
    - logs:eval_epoch.metric.MedR
    - logs:eval_epoch.metric.recall_at_1
    - logs:eval_epoch.metric.recall_at_5
    - logs:eval_epoch.metric.recall_at_10
